# Generated by Django 2.2.10 on 2020-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.RemoveField(
            model_name='todayonleave',
            name='status',
        ),
        migrations.AddField(
            model_name='todayonleave',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todayonleave',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
